//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NullHelper.rc
//
#define IDS_LIBDESCRIPTION              1
#define IDS_JBCATEGORY                  3
#define IDS_PARAMS                      4
#define IDS_SPIN                        5
#define IDS_NULL_CLASSNAME              6
#define IDS_XSCALE                      7
#define IDS_NULL_XSCALE                 7
#define IDS_YSCALE                      8
#define IDS_NULL_YSCALE                 8
#define IDS_ZSCALE                      9
#define IDS_NULL_ZSCALE                 9
#define IDS_LOCKXYZ                     10
#define IDS_NULL_LOCKXYZ                10
#define IDS_NULL_HELPER_PARAMETERS      11
#define IDS_DEFAULTNAME                 12
#define IDS_NULL_DEFAULTNAME            12
#define IDS_NULLSHAPE                   13
#define IDS_NULL_NULLSHAPE              13
#define IDS_DRAWDEPTH                   14
#define IDS_NULL_DRAWDEPTH              14
#define IDS_SOLIDSHADED                 15
#define IDS_NULL_SOLID                  15
#define IDS_NULL_DISPLAYLABEL           16
#define IDS_NULL_LABEL                  17
#define IDS_NULL_SHAPE_NONE             18
#define IDS_NULL_SHAPE_CROSS            19
#define IDS_NULL_SHAPE_JACK             20
#define IDS_NULL_SHAPE_BOX              21
#define IDS_NULL_SHAPE_VECTOR           22
#define IDS_NULL_SHAPE_SPHERE           23
#define IDS_NULL_SHAPE_TURTLE           24
#define IDS_LABEL_CLASSNAME             25
#define IDS_LABEL_HELPER_PARAMETERS     26
#define IDS_LABEL_DEFAULTNAME           27
#define IDS_LABEL_LABEL                 28
#define IDS_NULL_NONSCALING             29
#define IDS_NULL_DISPLAYPARENT          30
#define IDS_NULL_COLORAXIS              31
#define IDS_NULL_DRAWLINKLINE           32
#define IDS_NULL_LINKLINETYPE           33
#define IDS_NULL_DISPLAYNAME            34
#define IDS_NULL_MIXWIRECOLOR           35
#define IDS_NULL_CENTERPOINT            36
#define IDS_NULL_REF_NODES              37
#define IDS_NULL_REF_LINE               38
#define IDS_NULL_REF_DISTANCE           39
#define IDS_NULL_REF_LABEL              40
#define IDS_NULL_SHAPE_LINE             41
#define IDS_VERSION                     42
#define IDS_CATEGORY_BFD                43
#define IDS_CATEGORY_FOO                44
#define IDD_PANEL                       101
#define IDD_NULL_HELPER                 101
#define IDD_NULL_HELPER_OLD             102
#define IDD_NULL_HELPER1                102
#define IDD_LABEL_HELPER                103
#define IDD_ABOUT_BFD                   103
#define IDD_LABEL_CREATE                104
#define IDD_ABOUT_FOO                   104
#define IDD_NULL_HELPER2                105
#define IDB_COLOR_BLACK                 115
#define IDB_COLOR_BLUE                  116
#define IDB_COLOR_CYAN                  118
#define IDB_COLOR_GREEN                 119
#define IDB_COLOR_MAGENTA               120
#define IDB_COLOR_MUTEDBLUE             121
#define IDB_COLOR_MUTEDCYAN             122
#define IDB_COLOR_MUTEDGREEN            123
#define IDB_COLOR_MUTEDMAGENTA          124
#define IDB_COLOR_MUTEDRED              125
#define IDB_COLOR_MUTEDYELLOW           126
#define IDB_COLOR_RED                   127
#define IDB_COLOR_WHITE                 128
#define IDB_COLOR_YELLOW                129
#define IDB_COLOR_HELPERBLUE            130
#define IDB_FOOTOOLS                    133
#define IDC_CLOSEBUTTON                 1000
#define IDC_DOSTUFF                     1000
#define IDC_LOCKXYZ                     1001
#define IDC_XSCALE_LABEL                1002
#define IDC_YSCALE_LABEL                1003
#define IDC_ZSCALE_LABEL                1004
#define IDC_SHAPE_CROSS                 1005
#define IDC_SHAPE_BOX                   1006
#define IDC_SHAPE_SPHERE                1007
#define IDC_NULLSHAPE_GROUP             1008
#define IDC_SCALE_GROUP                 1009
#define IDC_QUICKWIRECOLOR_GROUP        1010
#define IDC_SHAPE_JACK                  1011
#define IDC_COLOR_MUTEDRED              1012
#define IDC_COLOR_MUTEDGREEN            1013
#define IDC_COLOR_MUTEDBLUE             1014
#define IDC_COLOR_MUTEDCYAN             1015
#define IDC_COLOR_MUTEDMAGENTA          1016
#define IDC_COLOR_MUTEDYELLOW           1017
#define IDC_COLOR_WHITE                 1018
#define IDC_COLOR_RED                   1019
#define IDC_COLOR_GREEN                 1020
#define IDC_COLOR_BLUE                  1021
#define IDC_COLOR_CYAN                  1022
#define IDC_ABOUT_WEB                   1022
#define IDC_COLOR_MAGENTA               1023
#define IDC_COLOR_YELLOW                1024
#define IDC_COLOR_BLACK                 1025
#define IDC_ABOUT_VERSION               1026
#define IDC_SHAPE_VECTOR                1027
#define IDC_SOLIDSHADED                 1028
#define IDC_SOLID                       1028
#define IDC_SHAPE_TURTLE                1029
#define IDC_DEPTH_STANDARD              1030
#define IDC_DEPTH_ONTOP                 1031
#define IDC_DEPTH_ONBOTTOM              1032
#define IDC_DEPTH_GROUP                 1033
#define IDC_LABEL_GROUP                 1036
#define IDC_DISPLAYLABEL                1038
#define IDC_LABEL                       1042
#define IDC_NULLSHAPE                   1046
#define IDC_NULL_LOCKXYZ                1048
#define IDC_NULL_XSCALE_EDIT            1049
#define IDC_NULL_XSCALE_SPIN            1050
#define IDC_NULL_YSCALE_EDIT            1051
#define IDC_NULL_YSCALE_SPIN            1052
#define IDC_NULL_ZSCALE_EDIT            1053
#define IDC_NULL_ZSCALE_SPIN            1054
#define IDC_NULL_ZSCALE_LABEL           1055
#define IDC_NULL_YSCALE_LABEL           1056
#define IDC_NULL_XSCALE_LABEL           1057
#define IDC_NULL_NULLSHAPE              1058
#define IDC_NULL_SOLID                  1059
#define IDC_NULL_DISPLAYLABEL           1060
#define IDC_NULL_LABEL                  1061
#define IDC_NULL_COLORAXIS              1062
#define IDC_NULL_DEPTH_ONTOP            1063
#define IDC_NULL_DISPLAYPARENT          1063
#define IDC_NULL_DISPLAYNAME            1064
#define IDC_NULL_SCALE_GROUP            1065
#define IDC_NULL_LABEL_GROUP            1066
#define IDC_NULL_REF_GROUP              1067
#define IDC_LABEL_DISPLAY_GROUP         1068
#define IDC_NULL_MIXWIRECOLOR           1068
#define IDC_LABEL_LABEL                 1069
#define IDC_NULL_REFADD                 1069
#define IDC_NULL_CENTERPOINT            1069
#define IDC_LABEL_SOLID                 1070
#define IDC_NULL_REFADD2                1070
#define IDC_LABEL_ICON                  1071
#define IDC_LABEL_DRAWLINK              1072
#define IDC_LABEL_AUTOLINK              1073
#define IDC_LABEL_CREATE_GROUP          1074
#define IDC_LABEL_LABEL_GROUP           1075
#define IDC_LABEL_LABEL_GROUP2          1076
#define IDC_LABEL_PREFIX_NODE           1079
#define IDC_LABEL_PREFIX_PARENT         1080
#define IDC_LABEL_PREFIX_NONE           1081
#define IDC_LABEL_PREFIX_GROUP          1082
#define IDC_NONSCALING                  1083
#define IDC_DISPLAYPARENT               1084
#define IDC_LINE_STRAIGHT               1085
#define IDC_LINE_BENT                   1086
#define IDC_CHECK1                      1088
#define IDC_TARGETNODE                  1089
#define IDC_NULL_DRAWLINKLINE           1090
#define IDC_NULL_REFLINE                1091
#define IDC_NULL_REFDISTANCE            1092
#define IDC_NULL_COLOR01                1095
#define IDC_NULL_COLOR02                1096
#define IDC_NULL_COLOR03                1097
#define IDC_NULL_COLOR04                1098
#define IDC_NULL_COLOR05                1099
#define IDC_NULL_COLOR06                1100
#define IDC_NULL_COLOR07                1101
#define IDC_NULL_COLOR08                1102
#define IDC_NULL_COLOR09                1103
#define IDC_NULL_COLOR10                1104
#define IDC_NULL_COLOR11                1105
#define IDC_NULL_COLOR12                1106
#define IDC_NULL_COLOR13                1107
#define IDC_NULL_COLOR14                1108
#define IDC_NULL_REF_LIST               1109
#define IDC_NULL_REF_LINE               1110
#define IDC_NULL_REF_DISTANCE           1111
#define IDC_NULL_REF_ADD                1112
#define IDC_NULL_REF_REMOVE             1113
#define IDC_NULL_REF_LABEL              1114
#define IDC_COLOR                       1456
#define IDC_EDIT                        1490
#define IDC_XSCALE_EDIT                 1490
#define IDC_YSCALE_EDIT                 1491
#define IDC_ZSCALE_EDIT                 1492
#define IDC_SPIN                        1496
#define IDC_XSCALE_SPIN                 1496
#define IDC_YSCALE_SPIN                 1497
#define IDC_ZSCALE_SPIN                 1498

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1113
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
